/*! 
* DevExtreme
* Version: 14.2.7
* Build date: Apr 17, 2015
*
* Copyright (c) 2011 - 2014 Developer Express Inc. ALL RIGHTS RESERVED
* EULA: https://www.devexpress.com/Support/EULAs/DevExtreme.xml
*/

Globalize.addCultureInfo("de", {messages: {
        Yes: "Ja",
        No: "Nein",
        Cancel: "Abbrechen",
        Clear: "Löschen",
        Done: "Fertig",
        Loading: "Laden...",
        Select: "Auswählen...",
        Search: "Suchen...",
        Back: "Zurück",
        OK: "OK",
        "dxCollectionWidget-noDataText": "Keine Daten verfügbar",
        "validation-required": "Pflichtfeld",
        "validation-required-formatted": "{0} ist ein Pflichtfeld",
        "validation-numeric": "Der Wert muss eine Zahl sein",
        "validation-numeric-formatted": "{0} muss eine Zahl sein",
        "validation-range": "Der Wert ist nicht im gültigen Bereich",
        "validation-range-formatted": "{0} ist nicht im gültigen Bereich",
        "validation-stringLength": "Die Länge des Wertes ist nicht korrekt",
        "validation-stringLength-formatted": "Die Länge von {0} ist nicht korrekt",
        "validation-custom": "Der Wert ist ungültig",
        "validation-custom-formatted": "{0} ist ungültig",
        "validation-compare": "Der Wert ist unpassend",
        "validation-compare-formatted": "{0} ist unpassend",
        "validation-pattern": "Der Wert passt nicht zum Muster",
        "validation-pattern-formatted": "{0} passt nicht zum Muster",
        "validation-email": "Die Email-Adresse ist ungültig",
        "validation-email-formatted": "{0} ist ungültig"
    }});
Globalize.addCultureInfo("de", {messages: {
        "dxLookup-searchPlaceholder": "Minimale Anzahl Zeichen: {0}",
        "dxList-pullingDownText": "Zum Aktualisieren nach unten ziehen",
        "dxList-pulledDownText": "Zum Aktualisieren loslassen",
        "dxList-refreshingText": "Aktualisiere...",
        "dxList-pageLoadingText": "Laden...",
        "dxList-nextButtonText": "Mehr",
        "dxList-selectAll": "Alles auswählen",
        "dxListEditDecorator-delete": "Entfernen",
        "dxListEditDecorator-more": "Mehr",
        "dxScrollView-pullingDownText": "Zum Aktualisieren nach unten ziehen",
        "dxScrollView-pulledDownText": "Zum Aktualisieren loslassen",
        "dxScrollView-refreshingText": "Aktualisiere...",
        "dxScrollView-reachBottomText": "Laden...",
        "dxDateBox-simulatedDataPickerTitleTime": "Zeit auswählen",
        "dxDateBox-simulatedDataPickerTitleDate": "Datum auswählen",
        "dxDateBox-simulatedDataPickerTitleDateTime": "Datum und Zeit auswählen",
        "dxDateBox-validation-datetime": "Der Wert muss ein Datum oder eine Uhrzeit sein",
        "dxFileUploader-selectFile": "Datei auswählen",
        "dxFileUploader-dropFile": "oder hierher ziehen",
        "dxFileUploader-bytes": "Bytes",
        "dxFileUploader-kb": "kb",
        "dxFileUploader-Mb": "Mb",
        "dxFileUploader-Gb": "Gb"
    }});

Globalize.addCultureInfo("de", {messages: {
        "dxDataGrid-columnChooserTitle": "Spaltenauswahl",
        "dxDataGrid-columnChooserEmptyText": "Ziehen Sie Spalten hierhin, um sie zu verstecken",
        "dxDataGrid-groupContinuesMessage": "Weiter auf der nächsten Seite",
        "dxDataGrid-groupContinuedMessage": "Weiter von der vorherigen Seite",
        "dxDataGrid-editingEditRow": "Bearbeiten",
        "dxDataGrid-editingSaveRowChanges": "Speichern",
        "dxDataGrid-editingCancelRowChanges": "Abbrechen",
        "dxDataGrid-editingDeleteRow": "Entfernen",
        "dxDataGrid-editingUndeleteRow": "Wiederherstellen",
        "dxDataGrid-editingConfirmDeleteMessage": "Sind Sie sicher, dass Sie diesen Datensatz löschen wollen?",
        "dxDataGrid-editingConfirmDeleteTitle": "",
        "dxDataGrid-groupPanelEmptyText": "Ziehen Sie eine Spalte hierhin, um danach zu gruppieren",
        "dxDataGrid-noDataText": "Keine Daten",
        "dxDataGrid-searchPanelPlaceholder": "Suchen...",
        "dxDataGrid-filterRowShowAllText": "(Alle)",
        "dxDataGrid-filterRowResetOperationText": "Zurücksetzen",
        "dxDataGrid-filterRowOperationEquals": "Ist gleich",
        "dxDataGrid-filterRowOperationNotEquals": "Ist nicht gleich",
        "dxDataGrid-filterRowOperationLess": "Kleiner als",
        "dxDataGrid-filterRowOperationLessOrEquals": "Kleiner oder gleich",
        "dxDataGrid-filterRowOperationGreater": "Größer als",
        "dxDataGrid-filterRowOperationGreaterOrEquals": "Größer oder gleich",
        "dxDataGrid-filterRowOperationStartsWith": "Beginnt mit",
        "dxDataGrid-filterRowOperationContains": "Enthält",
        "dxDataGrid-filterRowOperationNotContains": "Enthält nicht",
        "dxDataGrid-filterRowOperationEndsWith": "Endet mit",
        "dxDataGrid-applyFilterText": "Filter anwenden",
        "dxDataGrid-trueText": "wahr",
        "dxDataGrid-falseText": "falsch",
        "dxDataGrid-sortingAscendingText": "Aufsteigend sortieren",
        "dxDataGrid-sortingDescendingText": "Absteigend sortieren",
        "dxDataGrid-sortingClearText": "Sortierung aufheben",
        "dxDataGrid-editingSaveAllChanges": "Änderungen speichern",
        "dxDataGrid-editingCancelAllChanges": "Änderungen verwerfen",
        "dxDataGrid-editingAddRow": "Neue Zeile",
        "dxDataGrid-summaryMin": "Min: {0}",
        "dxDataGrid-summaryMinOtherColumn": "Minimum von {1} ist {0}",
        "dxDataGrid-summaryMax": "Max: {0}",
        "dxDataGrid-summaryMaxOtherColumn": "Maximum von {1} ist {0}",
        "dxDataGrid-summaryAvg": "Ø: {0}",
        "dxDataGrid-summaryAvgOtherColumn": "Durchschnitt von {1} ist {0}",
        "dxDataGrid-summarySum": "Summe: {0}",
        "dxDataGrid-summarySumOtherColumn": "Summe von {1} ist {0}",
        "dxDataGrid-summaryCount": "Anzahl: {0}",
        "dxPager-infoText": "Seite {0} von {1}",
        "dxSwitch-onText": "EIN",
        "dxSwitch-offText": "AUS"
    }});
