/*! 
* DevExtreme
* Version: 14.2.7
* Build date: Apr 17, 2015
*
* Copyright (c) 2011 - 2014 Developer Express Inc. ALL RIGHTS RESERVED
* EULA: https://www.devexpress.com/Support/EULAs/DevExtreme.xml
*/

Globalize.addCultureInfo("ru", {messages: {
        Yes: "Да",
        No: "Нет",
        Cancel: "Отмена",
        Clear: "Очистить",
        Done: "Готово",
        Loading: "Загрузка...",
        Select: "Выбрать...",
        Search: "Поиск",
        Back: "Назад",
        OK: "OK",
        "dxCollectionWidget-noDataText": "Нет данных для отображения",
        "validation-required": "Поле необходимо заполнить",
        "validation-required-formatted": "Необходимо заполнить: {0}",
        "validation-numeric": "Значение должно быть числом",
        "validation-numeric-formatted": "Значение поля {0} должно быть числом",
        "validation-range": "Значение поля не входит в диапазон",
        "validation-range-formatted": "Значение поля {0} не входит в диапазон",
        "validation-stringLength": "Неверная длина значения в поле",
        "validation-stringLength-formatted": "Неверная длина значения в поле {0}",
        "validation-custom": "Недопустимое значение",
        "validation-custom-formatted": "Недопустимое значение: {0}",
        "validation-compare": "Значения полей не соответствуют друг другу.",
        "validation-compare-formatted": "Значение поля {0} не соответствует",
        "validation-pattern": "Значение не соответствует шаблону",
        "validation-pattern-formatted": "Значение поля {0} не соответствует шаблону",
        "validation-email": "Недопустимое значение email",
        "validation-email-formatted": "Недопустимое значениe {0}"
    }});
Globalize.addCultureInfo("ru", {messages: {
        "dxLookup-searchPlaceholder": "Минимальное количество символов: {0}",
        "dxList-pullingDownText": "Потяните, чтобы обновить...",
        "dxList-pulledDownText": "Отпустите, чтобы обновить...",
        "dxList-refreshingText": "Обновление...",
        "dxList-pageLoadingText": "Загрузка...",
        "dxList-nextButtonText": "Далее",
        "dxList-selectAll": "Выбрать все",
        "dxListEditDecorator-delete": "Удалить",
        "dxListEditDecorator-more": "Еще",
        "dxScrollView-pullingDownText": "Потяните, чтобы обновить...",
        "dxScrollView-pulledDownText": "Отпустите, чтобы обновить...",
        "dxScrollView-refreshingText": "Обновление...",
        "dxScrollView-reachBottomText": "Загрузка...",
        "dxDateBox-simulatedDataPickerTitleTime": "Выберите время",
        "dxDateBox-simulatedDataPickerTitleDate": "Выберите дату",
        "dxDateBox-simulatedDataPickerTitleDateTime": "Выберите дату и время",
        "dxDateBox-validation-datetime": "Значение должно быть датой/временем",
        "dxFileUploader-selectFile": "Выберите файл",
        "dxFileUploader-dropFile": "или Перетащите файл сюда",
        "dxFileUploader-bytes": "байт",
        "dxFileUploader-kb": "кБ",
        "dxFileUploader-Mb": "МБ",
        "dxFileUploader-Gb": "ГБ",
        "dxSwitch-onText": "ВКЛ",
        "dxSwitch-offText": "ВЫКЛ"
    }});

Globalize.addCultureInfo("ru", {messages: {
        "dxDataGrid-columnChooserTitle": "Выбор столбцов",
        "dxDataGrid-columnChooserEmptyText": "Перетащите столбец сюда, чтобы скрыть его",
        "dxDataGrid-groupContinuesMessage": "Продолжение на следующей странице",
        "dxDataGrid-groupContinuedMessage": "Продолжение с предыдущей страницы",
        "dxDataGrid-editingEditRow": "Редактировать",
        "dxDataGrid-editingSaveRowChanges": "Сохранить",
        "dxDataGrid-editingCancelRowChanges": "Отменить",
        "dxDataGrid-editingDeleteRow": "Удалить",
        "dxDataGrid-editingUndeleteRow": "Восстановить",
        "dxDataGrid-editingConfirmDeleteMessage": "Вы уверены, что хотите удалить эту запись?",
        "dxDataGrid-editingConfirmDeleteTitle": "",
        "dxDataGrid-groupPanelEmptyText": "Перетащите столбец сюда, чтобы сгруппировать по нему",
        "dxDataGrid-noDataText": "Нет данных",
        "dxDataGrid-searchPanelPlaceholder": "Искать...",
        "dxDataGrid-filterRowShowAllText": "(Все)",
        "dxDataGrid-filterRowResetOperationText": "Сбросить",
        "dxDataGrid-filterRowOperationEquals": "Равно",
        "dxDataGrid-filterRowOperationNotEquals": "Не равно",
        "dxDataGrid-filterRowOperationLess": "Меньше",
        "dxDataGrid-filterRowOperationLessOrEquals": "Меньше или равно",
        "dxDataGrid-filterRowOperationGreater": "Больше",
        "dxDataGrid-filterRowOperationGreaterOrEquals": "Больше или равно",
        "dxDataGrid-filterRowOperationStartsWith": "Начинается с",
        "dxDataGrid-filterRowOperationContains": "Содержит",
        "dxDataGrid-filterRowOperationNotContains": "Не содержит",
        "dxDataGrid-filterRowOperationEndsWith": "Заканчивается на",
        "dxDataGrid-applyFilterText": "Применить фильтр",
        "dxDataGrid-trueText": "Да",
        "dxDataGrid-falseText": "Нет",
        "dxDataGrid-sortingAscendingText": "Сортировать по возрастанию",
        "dxDataGrid-sortingDescendingText": "Сортировать по убыванию",
        "dxDataGrid-sortingClearText": "Сбросить сортировку",
        "dxDataGrid-editingSaveAllChanges": "Сохранить изменения",
        "dxDataGrid-editingCancelAllChanges": "Отменить изменения",
        "dxDataGrid-editingAddRow": "Добавить строку",
        "dxDataGrid-summaryMin": "Мин: {0}",
        "dxDataGrid-summaryMinOtherColumn": "Мин по {1} : {0}",
        "dxDataGrid-summaryMax": "Макс: {0}",
        "dxDataGrid-summaryMaxOtherColumn": "Макс по {1} : {0}",
        "dxDataGrid-summaryAvg": "Срзнач: {0}",
        "dxDataGrid-summaryAvgOtherColumn": "Срзнач по {1} : {0}",
        "dxDataGrid-summarySum": "Сумм: {0}",
        "dxDataGrid-summarySumOtherColumn": "Сумм по {1} : {0}",
        "dxDataGrid-summaryCount": "Кол-во: {0}",
        "dxPager-infoText": "Страница {0} из {1}"
    }});
