/*! 
* DevExtreme
* Version: 14.2.7
* Build date: Apr 17, 2015
*
* Copyright (c) 2011 - 2014 Developer Express Inc. ALL RIGHTS RESERVED
* EULA: https://www.devexpress.com/Support/EULAs/DevExtreme.xml
*/

Globalize.addCultureInfo("ja", {messages: {
        Yes: "はい",
        No: "いいえ",
        Cancel: "キャンセル",
        Clear: "クリア",
        Done: "完了",
        Loading: "読み込み中…",
        Select: "選択…",
        Search: "検索",
        Back: "戻る",
        OK: "OK",
        "dxCollectionWidget-noDataText": "表示するデータがありません。",
        "validation-required": "必須",
        "validation-required-formatted": "{0} は必須です。",
        "validation-numeric": "数値を指定してください。",
        "validation-numeric-formatted": "{0} は数値でなければいけません。",
        "validation-range": "値が範囲外です",
        "validation-range-formatted": "{0} の長さが正しくありません。",
        "validation-stringLength": "値の長さが正しくありません。",
        "validation-stringLength-formatted": "{0} の長さが正しくありません",
        "validation-custom": "値が無効です。",
        "validation-custom-formatted": "{0} が無効です。",
        "validation-compare": "値が一致しません。",
        "validation-compare-formatted": " {0} が一致しません。",
        "validation-pattern": "値がパターンと一致しません",
        "validation-pattern-formatted": "{0} がパターンと一致しません",
        "validation-email": "電子メール アドレスが無効です。",
        "validation-email-formatted": "{0} が無効です。"
    }});
Globalize.addCultureInfo("ja", {messages: {
        "dxLookup-searchPlaceholder": "最低文字数: {0}",
        "dxList-pullingDownText": "引っ張って更新…",
        "dxList-pulledDownText": "指を離して更新…",
        "dxList-refreshingText": "更新中…",
        "dxList-pageLoadingText": "読み込み中…",
        "dxList-nextButtonText": "もっと表示する",
        "dxList-selectAll": "すべてを選択",
        "dxListEditDecorator-delete": "削除",
        "dxListEditDecorator-more": "もっと",
        "dxScrollView-pullingDownText": "引っ張って更新…",
        "dxScrollView-pulledDownText": "指を離して更新…",
        "dxScrollView-refreshingText": "更新中…",
        "dxScrollView-reachBottomText": "読み込み中",
        "dxDateBox-simulatedDataPickerTitleTime": "時刻を選択してください。",
        "dxDateBox-simulatedDataPickerTitleDate": "日付を選択してください。",
        "dxDateBox-simulatedDataPickerTitleDateTime": "日付と時刻を選択してください。",
        "dxDateBox-validation-datetime": "日付または時刻を指定してください。",
        "dxFileUploader-selectFile": "ファイルを選択",
        "dxFileUploader-dropFile": "またはファイルをこちらにドロップしてください。",
        "dxFileUploader-bytes": "バイト",
        "dxFileUploader-kb": "kb",
        "dxFileUploader-Mb": "Mb",
        "dxFileUploader-Gb": "Gb"
    }});

Globalize.addCultureInfo("ja", {messages: {
        "dxDataGrid-columnChooserTitle": "列の選択",
        "dxDataGrid-columnChooserEmptyText": "隠したい列のヘッダーをここにドラッグしてください。",
        "dxDataGrid-groupContinuesMessage": "次ページに続く",
        "dxDataGrid-groupContinuedMessage": "前ページから続く",
        "dxDataGrid-editingEditRow": "編集",
        "dxDataGrid-editingSaveRowChanges": "保存",
        "dxDataGrid-editingCancelRowChanges": "キャンセル",
        "dxDataGrid-editingDeleteRow": "削除",
        "dxDataGrid-editingUndeleteRow": "復元",
        "dxDataGrid-editingConfirmDeleteMessage": "このレコードを削 除してもよろしいですか?",
        "dxDataGrid-editingConfirmDeleteTitle": "",
        "dxDataGrid-groupPanelEmptyText": "グループ化したい列のヘッダーをここにドラッグしてください。",
        "dxDataGrid-noDataText": "データがありません",
        "dxDataGrid-searchPanelPlaceholder": "検索",
        "dxDataGrid-filterRowShowAllText": "(すべて)",
        "dxDataGrid-filterRowResetOperationText": "リセット",
        "dxDataGrid-filterRowOperationEquals": "指定の値に等しい",
        "dxDataGrid-filterRowOperationNotEquals": "指定の値に等しくない",
        "dxDataGrid-filterRowOperationLess": "指定の値より小さい",
        "dxDataGrid-filterRowOperationLessOrEquals": "指定の値以下",
        "dxDataGrid-filterRowOperationGreater": "指定の値より大きい",
        "dxDataGrid-filterRowOperationGreaterOrEquals": "指定の値以上",
        "dxDataGrid-filterRowOperationStartsWith": "指定の値で始まる",
        "dxDataGrid-filterRowOperationContains": "指定の値を含む",
        "dxDataGrid-filterRowOperationNotContains": "指定の値を含まない",
        "dxDataGrid-filterRowOperationEndsWith": "指定の値で終わる",
        "dxDataGrid-applyFilterText": "フィルターを適用",
        "dxDataGrid-trueText": "true",
        "dxDataGrid-falseText": "false",
        "dxDataGrid-sortingAscendingText": "昇順に並べ替え",
        "dxDataGrid-sortingDescendingText": "降順に並べ替え",
        "dxDataGrid-sortingClearText": "並べ替えをクリア",
        "dxDataGrid-editingSaveAllChanges": "変更を保存",
        "dxDataGrid-editingCancelAllChanges": "変更を破棄",
        "dxDataGrid-editingAddRow": "行を追加",
        "dxDataGrid-summaryMin": "Min: {0}",
        "dxDataGrid-summaryMinOtherColumn": "{1} の最小は {0}",
        "dxDataGrid-summaryMax": "Max: {0}",
        "dxDataGrid-summaryMaxOtherColumn": "{1} の最小は {0}",
        "dxDataGrid-summaryAvg": "Avg: {0}",
        "dxDataGrid-summaryAvgOtherColumn": "{1} の平均は {0}",
        "dxDataGrid-summarySum": "合計: {0}",
        "dxDataGrid-summarySumOtherColumn": "{1} の合計は {0}",
        "dxDataGrid-summaryCount": "総数: {0}",
        "dxPager-infoText": "ページ {0} / {1}",
        "dxSwitch-onText": "オン",
        "dxSwitch-offText": "オフ"
    }});
